### ISSUE TITLE
All weights?

### ISSUE THREAD

**Issue by davelab6** [philatype/Sen#1]
If the glyphs file has a Regular and Extrabold master, why not interpolate all the intermediate weights? :) 

http://www.impallari.com/familysteps/ can help you with this

**Comment by philatype** [comment]
Not sure what you mean. Are you suggesting more weights? The bold is already interpolated from the two masters.

**Comment by davelab6** [comment]
I mean like this: 

400 Regular
500 [Missing]
600 [Missing]
700 Bold
800 ExtraBold

**Comment by philatype** [comment]
Gotcha. My intent was to have just those three weights.

**Comment by davelab6** [comment]
I'm curious why you intend this? :)

**Comment by philatype** [comment]
Aesthetic decision, really. I don't feel like it is necessary to add any additional weights between Regular and Extrabold. Maybe some day in the future, it could benefit from a Light/ExtraLight, but it is what it is right now.

**Comment by Sam-Apostel** [comment]
I would love a light version of this font. I know I'm late to the conversation but I feel like this would extend the impact of Sen
